// Список призов за идеальное прохождение папок
export const CHAPTER_REWARDS = {
  basics: {
    wallpaper: 'space',
    wallpaperName: 'Космос',
    wallpaperNameEn: 'Space',
    achievement: 'FILTER',
    text: 'Ты прошёл основы идеально! Награда: обои «Космос» и ачивка «Первое знамение».',
    textEn: 'You mastered basics perfectly! Reward: "Space" wallpaper and "First signal" achievement.',
  },
  cleaning: {
    wallpaper: 'cyberpunk',
    wallpaperName: 'Киберпанк',
    wallpaperNameEn: 'Cyberpunk',
    achievement: 'CLEAN',
    text: 'Идеальная чистка! Награда: обои «Киберпанк» и ачивка «Чистюля».',
    textEn: 'Perfect cleaning! Reward: "Cyberpunk" wallpaper and "Cleaner" achievement.',
  },
  grouping: {
    wallpaper: 'neon',
    wallpaperName: 'Неон',
    wallpaperNameEn: 'Neon',
    achievement: 'CONNECT',
    text: 'Идеальная группировка! Награда: обои «Неон» и ачивка «Связующий».',
    textEn: 'Perfect grouping! Reward: "Neon" wallpaper and "Connector" achievement.',
  },
  merging: {
    wallpaper: 'sunset',
    wallpaperName: 'Закат',
    wallpaperNameEn: 'Sunset',
    achievement: 'DIVIDE',
    text: 'Идеальное соединение! Награда: обои «Закат» и ачивка «Разделяй и понимай».',
    textEn: 'Perfect merge! Reward: "Sunset" wallpaper and "Divide and understand" achievement.',
  },
  datetime: {
    wallpaper: 'forest',
    wallpaperName: 'Лес',
    wallpaperNameEn: 'Forest',
    achievement: 'COFFEE',
    text: 'Идеальные даты! Награда: обои «Лес» и ачивка «Ночной дожор».',
    textEn: 'Perfect dates! Reward: "Forest" wallpaper and "Night owl" achievement.',
  },
  strings: {
    wallpaper: 'ocean',
    wallpaperName: 'Океан',
    wallpaperNameEn: 'Ocean',
    achievement: 'NAN',
    text: 'Идеальные тексты! Награда: обои «Океан» и ачивка «NaN-невидимка».',
    textEn: 'Perfect strings! Reward: "Ocean" wallpaper and "NaN-invisible" achievement.',
  },
  bosses: {
    wallpaper: 'matrix',
    wallpaperName: 'Матрица',
    wallpaperNameEn: 'Matrix',
    achievement: 'OVERFIT',
    text: 'Боссы побеждены идеально! Награда: обои «Матрица» и ачивка «Идеальный на трейне».',
    textEn: 'Bosses defeated perfectly! Reward: "Matrix" wallpaper and "Perfect on train" achievement.',
  },
};
